services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["pnpm", "web:dev"]
    volumes:
      - ./web/src:/app/web/src
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: radcomm
      POSTGRES_PASSWORD: radcomm
      POSTGRES_DB: radcomm
    ports:
      - "5432:5432"
