services:
  storefront:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["pnpm", "storefront:dev"]
    volumes:
      - ./storefront/src:/app/storefront/src
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: radcomm
      POSTGRES_PASSWORD: radcomm
      POSTGRES_DB: radcomm
    ports:
      - "5432:5432"
