services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["pnpm", "web:dev"]
    volumes:
      - ./apps/web/src:/app/apps/web/src
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
